homeassistant:
  # Name of the location where Home Assistant is running
  name: Downstairs Door Controller
  # Location required to calculate the time the sun rises and sets
  latitude: 35.7125
  longitude: -88.7021
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 157
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# View all events in a logbook
logbook:

binary_sensor:
  - platform: rpi_gpio
    invert_logic: true
    ports:
      26: Down Test Door 1
      19: Down Test Door 2

group:
  downstairs_doors:
    name: Downstairs Doors
    view: no
    entities:
      - binary_sensor.down_test_door_1
      - binary_sensor.down_test_door_2
      - binary_sensor.down_test_door_3

mqtt:
  broker: !secret mqtt_host
  port: 1883
  client_id: hass_down
  keepalive: 60
  username: !secret mqtt_user
  password: !secret mqtt_pass    

mqtt_eventstream:
  publish_topic: slaves/downstairs/doors
  subscribe_topic: master
