homeassistant:
  # Name of the location where Home Assistant is running
  name: Downstairs Door Controller
  # Location required to calculate the time the sun rises and sets
  latitude: 35.7125
  longitude: -88.7021
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 157
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# View all events in a logbook
logbook:

binary_sensor:
  - platform: rpi_gpio
    invert_logic: true
    ports:
      2: Front Entry Door
      3: Side Entry Door
      4: Back Entry Door
      17: Garage Entry Door
      27: Master Bedroom Door
      22: Master Bath Door
      10: Master Closet 1 Door
      9: Master Closet 2 Door
      11: Master Toilet Door
      5: Pantry Door
      6: Laundry Door
      13: Half Bath Door
      19: Guest Bedroom Door
      26: Guest Bathroom Door
      14: Guest Closet Door
      15: Coat Closet Door
      18: Garage Door 1
      23: Garage Door 2
      #24:
      #25:
      #8:
      7: Dining Room Window
      12: Guest Bedroom Window
      16: Master Bedroom Window
      20: Breakfast Area Window
      21: Living Room Window

group:
  downstairs_doors:
    name: Downstairs Doors
    view: no
    entities:
      - binary_sensor.front_entry_door
      - binary_sensor.side_entry_door
      - binary_sensor.garage_entry_door
      - binary_sensor.back_entry_door
      - binary_sensor.master_bedroom_door
      - binary_sensor.master_bath_door
      - binary_sensor.master_closet_1_door
      - binary_sensor.master_closet_2_door
      - binary_sensor.master_toilet_door
      - binary_sensor.pantry_door
      - binary_sensor.laundry_door
      - binary_sensor.half_bath_door
      - binary_sensor.guest_bedroom_door
      - binary_sensor.guest_bathroom_door
      - binary_sensor.guest_closet_door
      - binary_sensor.coat_closet_door
      - binary_sensor.garage_door_1
      - binary_sensor.garage_door_2
  downstairs_windows: 
    name: Downstairs Windows
    view: no
    entities:
      - binary_sensor.dining_room_window
      - binary_sensor.guest_bedroom_window
      - binary_sensor.master_bedroom_window
      - binary_sensor.breakfast_area_window
      - binary_sensor.living_room_window

mqtt:
  broker: !secret mqtt_host
  port: 1883
  client_id: hass_down
  keepalive: 60
  username: !secret mqtt_user
  password: !secret mqtt_pass    

mqtt_eventstream:
  publish_topic: slaves/downstairs/doors
  subscribe_topic: master/none
